version: '3.8'

services:
  # 1. CADDY (HTTPS Server & Reverse Proxy)
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

  # 2. DATABASE (MySQL)
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pbl6_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build: ./PBL6
    restart: always
    depends_on:
      - backend

  # 3. BACKEND (NodeJS)
  backend:
    build: ./PBL6_BE
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_PASS=123456
      - DB_NAME=pbl6_db
      - DB_PORT=3306
      - PORT=8080
      - NODE_ENV=development
      - AI_SERVICE_URL=http://ai_service:5000
      - MAIL_USER=phuonghaleduy@gmail.com
      - MAIL_PASS=yequ yzgt eati wnih
      - JWT_SECRET=mysecretkey123
      - BASE_URL=https://sip-in-ease.duckdns.org
    depends_on:
      - db
      - ai_service

  # 4. AI SERVICE (Flask)
  ai_service:
    build: .
    volumes:
      - ./Data:/app/Data
    deploy:
      resources:
        limits:
          memory: 1G

# Khai báo nơi lưu dữ liệu
volumes:
  mysql_data:
  caddy_data:
  caddy_config: